### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by maxammann** [JorianWoltjer/jorianwoltjer.com#1]
Is there already a way to subscribe to your blog?

I tried the usual paths to find an RSS feed but failed.

**Comment by JorianWoltjer** [comment]
Thanks again for the suggestion. I just implemented the RSS Feed as I think it's a good way to keep updated with new posts. There is now an RSS icon on the main blog page to go there ([/blog/rss.xml](https://jorianwoltjer.com/blog/rss.xml)). 

Commit: https://github.com/JorianWoltjer/jorianwoltjer.com/commit/954ec7f7c5d7831c22ec6dae819a3cf4a41c3bfa

**Comment by maxammann** [comment]
Thank you! Just subscribed! :)
